name: Azure Login Test
run-name: ${{ github.actor }} is testing out GitHub Actions 
on:
  push:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  Test-Login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Login to Azure
        env:
          AZURE_APP_ID_URI: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal --username "$AZURE_APP_ID_URI" --password "$AZURE_CLIENT_SECRET" --tenant "$AZURE_TENANT_ID"

