name: copilot-deploy-infra

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      AZURE_OPENAI_ENDPOINT:
        required: true
    outputs:
      deployment-id:
        description: "The Id of the current deployment."
        value: ${{jobs.deploy.outputs.deployment-id}}

jobs:
  deploy:
    environment: ${{inputs.ENVIRONMENT}}
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - { dotnet: "6.0", configuration: Release, os: ubuntu-latest }
    outputs:
      deployment-id: ${{steps.deployment-id.outputs.deployment_name}}

    runs-on: ${{ matrix.os }}
    steps:
      - name: Generate Deployment Id
        id: deployment-id
        run: echo "deployment_name=${{ vars.CC_DEPLOYMENT_NAME }}-$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        with:
          clean: true

      - name: Login to Azure
        env:
          AZURE_APP_ID_URI: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          az login --service-principal --username="$AZURE_APP_ID_URI" --password="$AZURE_CLIENT_SECRET" --tenant="$AZURE_TENANT_ID"

      - name: deploy-infra
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            AI_SERVICE_KEY=$(az cognitiveservices account keys list --name ${{vars.AZUREOPENAI__NAME}} --resource-group ${{vars.AZUREOPENAI_DEPLOYMENT_GROUP_NAME}} | jq -r '.key1')
            echo "::add-mask::$AI_SERVICE_KEY"
            scripts/deploy/deploy-azure.sh --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --resource-group ${{vars.CC_DEPLOYMENT_GROUP_NAME}} --deployment-name ${{steps.deployment-id.outputs.deployment_name}} --region ${{vars.CC_DEPLOYMENT_REGION}} --client-id ${{vars.BACKEND_CLIENT_ID}} --tenant-id ${{secrets.AZURE_TENANT_ID}} --instance ${{vars.AZURE_INSTANCE}} --ai-service AzureOpenAI --ai-endpoint ${{secrets.AZURE_OPENAI_ENDPOINT}} --ai-service-key $AI_SERVICE_KEY --app-service-sku ${{vars.WEBAPP_API_SKU}} --no-deploy-package --debug-deployment
